### ISSUE TITLE
How to use SRigL to adapt "N:M sparsity"

### ISSUE THREAD

**Issue by erwangccc** [calgaryml/condensed-sparsity#64]
Hi, @evcu @yanii 

Thanks for your great work first.
The paper said that:

> This structure is a particular case of “N:M sparsity” which requiresN out ofM consecutive weights to be non-zero

So i want to know that how to use SRigL to adapt "N:M sparsity"(such as 2:4/4:8 Structured Sparsity). 

Thanks in advance.

**Comment by mklasby** [comment]
Hi @erwangccc, 
Currently we have not implemented arbritary N:M support, only the constant fan-in. If you're willing to migrate to `jax`, I suggest checking out the `jaxpruner` library which does support arbritarty N:M sparisty. We are working on migrating methods from this repo in that library as well. 

Jaxpruner: https://github.com/google-research/jaxpruner
